apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ include "stock-demo.namespace" . }}
  labels:
    {{- include "stock-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: stock-backend
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app.kubernetes.io/name: stock-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 8080
