apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
  namespace: {{ include "stock-demo.namespace" . }}
  labels:
    {{- include "stock-demo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
