apiVersion: v1
kind: Namespace
metadata:
  name: stock-demo
  labels:
    team: semea
    app: stock-demo
    # Datadog Admission Controller will inject APM automatically
    admission.datadoghq.com/enabled: "true"
